---
version: '3.5'
services:
  replicator:
    image: confluentinc/cp-enterprise-replicator-executable:${TAG}
    hostname: replicator
    container_name: replicator
    volumes:
        - ../../ccloud/replicator/executable-onprem-to-cloud-consumer-repro-avro.properties:/etc/replicator/consumer.properties
        - ../../ccloud/replicator/executable-onprem-to-cloud-producer-repro-avro.properties:/etc/replicator/producer.properties
        - ../../ccloud/replicator/executable-onprem-to-cloud-replicator-repro-avro.properties:/etc/replicator/replication.properties
    environment:
      WHITELIST: executable-products-avro


  control-center:
     environment:
      CONTROL_CENTER_CONNECT_CLUSTER: http://replicator:8083