---
version: '3.5'
services:
  connect-us:
    image: confluentinc/cp-enterprise-replicator-executable:${TAG}
    volumes:
        - ../../replicator/executable/consumer-us-plaintext.properties:/etc/replicator/consumer.properties
        - ../../replicator/executable/producer-us-plaintext.properties:/etc/replicator/producer.properties
        - ../../replicator/executable/replication-us.properties:/etc/replicator/replication.properties

  connect-europe:
    image: confluentinc/cp-enterprise-replicator-executable:${TAG}
    volumes:
        - ../../replicator/executable/consumer-europe-plaintext.properties:/etc/replicator/consumer.properties
        - ../../replicator/executable/producer-europe-plaintext.properties:/etc/replicator/producer.properties
        - ../../replicator/executable/replication-europe.properties:/etc/replicator/replication.properties

  control-center:
     environment:
      CONTROL_CENTER_CONNECT_EUROPE_CLUSTER: http://connect-europe:18083 # rest api for the replicator executables
      CONTROL_CENTER_CONNECT_US_CLUSTER: http://connect-us:18083 # rest api for the replicator executables